lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)PerSec><>Count"
    name: kafka_server_$1_$2_total
    type: COUNTER
    help: "Kafka server $1 $2 per second count"
  - pattern: "kafka.server<type=(.+), name=(.+)PerSec, topic=(.+)><>Count"
    name: kafka_server_$1_$2_total
    labels:
      topic: "$3"
    type: COUNTER
    help: "Kafka server $1 $2 per second count"

